/* Generated by Yosys 0.5 (git sha1 c3c9fbf, gcc 4.9.2-10ubuntu5 -O2 -fstack-protector-strong -fPIC -Os) */
///Hello world
(* src = "./Tests/mux.v:1" *)
module mux(a, b, sel, o);
  (* src = "./Tests/mux.v:1" *)
  input a;
  (* src = "./Tests/mux.v:1" *)
  input b;
  (* src = "./Tests/mux.v:1" *)
  output o;
  (* src = "./Tests/mux.v:1" *)
  input sel;
  \$_MUX_  _0_ (
    .A(a),
    .B(b),
    .S(sel),
    .Y(o)
  );
endmodule
