######################################################################
# Automatically generated by qmake (3.0) Wed May 6 13:26:18 2015
######################################################################

TEMPLATE = app
TARGET = STA
INCLUDEPATH += .

# Input
SOURCES += STA.cpp
