######################################################################
# Automatically generated by qmake (3.0) Wed May 6 22:15:26 2015
######################################################################

TEMPLATE = app
TARGET = STA
INCLUDEPATH += .

# Input
SOURCES += STA.cpp

CONFIG += c++11
#QMAKE_CXXFLAGS += -std=c++11