/* Generated by Yosys 0.5 (git sha1 c3c9fbf, gcc 4.9.2-10ubuntu5 -O2 -fstack-protector-strong -fPIC -Os) */

(* src = "mux.v:1" *)
module mux(a, b, sel, o);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  (* src = "mux.v:1" *)
  input a;
  (* src = "mux.v:1" *)
  input b;
  (* src = "mux.v:1" *)
  output o;
  (* src = "mux.v:1" *)
  input sel;
  \$_MUX_  _8_ (
    .A(_4_),
    .B(_5_),
    .S(_6_),
    .Y(_7_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign _2_ = sel;
  assign o = _3_;
  assign _4_ = a;
  assign _5_ = b;
  assign _6_ = sel;
  assign _3_ = _7_;
endmodule
