/* Generated by Yosys 0.5 (git sha1 c3c9fbf, gcc 4.9.2-10ubuntu5 -O2 -fstack-protector-strong -fPIC -Os) */

(* src = "PmodI2S_FSM.v:21" *)
module PmodI2S_FSM(start, i2s_en, clk_sclk, rst, cntr_ncs, cntr_load);
  (* src = "PmodI2S_FSM.v:37" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [3:0] _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  (* src = "PmodI2S_FSM.v:24" *)
  input clk_sclk;
  (* src = "PmodI2S_FSM.v:31" *)
  wire [3:0] cnt;
  (* src = "PmodI2S_FSM.v:27" *)
  output cntr_load;
  (* src = "PmodI2S_FSM.v:26" *)
  output cntr_ncs;
  (* src = "PmodI2S_FSM.v:23" *)
  input i2s_en;
  (* src = "PmodI2S_FSM.v:25" *)
  input rst;
  (* src = "PmodI2S_FSM.v:22" *)
  input start;
  (* onehot = 32'd 1 *)
  wire [3:0] state;
  INVX1 _28_ (
    .A(rst),
    .Y(_01_)
  );
  INVX1 _29_ (
    .A(clk_sclk),
    .Y(_27_)
  );
  INVX1 _30_ (
    .A(state[0]),
    .Y(_02_)
  );
  NOR2X1 _31_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_03_)
  );
  XNOR2X1 _32_ (
    .A(_03_),
    .B(cnt[2]),
    .Y(_04_)
  );
  NAND2X1 _33_ (
    .A(_02_),
    .B(_04_),
    .Y(_00_[2])
  );
  NAND2X1 _34_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_05_)
  );
  NOR2X1 _35_ (
    .A(state[0]),
    .B(_03_),
    .Y(_06_)
  );
  NAND2X1 _36_ (
    .A(_05_),
    .B(_06_),
    .Y(_00_[1])
  );
  NAND2X1 _37_ (
    .A(cnt[0]),
    .B(_02_),
    .Y(_00_[0])
  );
  NAND2X1 _38_ (
    .A(state[1]),
    .B(start),
    .Y(_07_)
  );
  NOR2X1 _39_ (
    .A(cnt[3]),
    .B(cnt[2]),
    .Y(_08_)
  );
  AND2X2 _40_ (
    .A(_03_),
    .B(_08_),
    .Y(_09_)
  );
  NAND2X1 _41_ (
    .A(state[2]),
    .B(_09_),
    .Y(_10_)
  );
  NAND2X1 _42_ (
    .A(_07_),
    .B(_10_),
    .Y(_22_[1])
  );
  NAND2X1 _43_ (
    .A(_03_),
    .B(_08_),
    .Y(_11_)
  );
  NAND2X1 _44_ (
    .A(state[2]),
    .B(_11_),
    .Y(_12_)
  );
  NAND2X1 _45_ (
    .A(start),
    .B(i2s_en),
    .Y(_13_)
  );
  OR2X2 _46_ (
    .A(_13_),
    .B(_02_),
    .Y(_14_)
  );
  NAND2X1 _47_ (
    .A(_14_),
    .B(_12_),
    .Y(_22_[2])
  );
  NAND2X1 _48_ (
    .A(state[0]),
    .B(_13_),
    .Y(_15_)
  );
  INVX1 _49_ (
    .A(start),
    .Y(_16_)
  );
  NAND2X1 _50_ (
    .A(state[1]),
    .B(_16_),
    .Y(_17_)
  );
  NAND2X1 _51_ (
    .A(_17_),
    .B(_15_),
    .Y(_22_[0])
  );
  INVX1 _52_ (
    .A(cnt[2]),
    .Y(_18_)
  );
  NAND2X1 _53_ (
    .A(_18_),
    .B(_03_),
    .Y(_19_)
  );
  NAND2X1 _54_ (
    .A(cnt[3]),
    .B(_19_),
    .Y(_20_)
  );
  AND2X2 _55_ (
    .A(_11_),
    .B(_02_),
    .Y(_21_)
  );
  NAND2X1 _56_ (
    .A(_20_),
    .B(_21_),
    .Y(_00_[3])
  );
  OR2X2 _57_ (
    .A(state[0]),
    .B(state[1]),
    .Y(cntr_ncs)
  );
  BUFX2 _58_ (
    .A(_27_),
    .Y(_25_)
  );
  BUFX2 _59_ (
    .A(_27_),
    .Y(_23_)
  );
  BUFX2 _60_ (
    .A(_01_),
    .Y(_24_)
  );
  BUFX2 _61_ (
    .A(_01_),
    .Y(_26_)
  );
  DFFNEGX1 _62_ (
    .CLK(clk_sclk),
    .D(_00_[0]),
    .Q(cnt[0])
  );
  DFFNEGX1 _63_ (
    .CLK(clk_sclk),
    .D(_00_[1]),
    .Q(cnt[1])
  );
  DFFNEGX1 _64_ (
    .CLK(clk_sclk),
    .D(_00_[2]),
    .Q(cnt[2])
  );
  DFFNEGX1 _65_ (
    .CLK(clk_sclk),
    .D(_00_[3]),
    .Q(cnt[3])
  );
  DFFSR _66_ (
    .CLK(_25_),
    .D(_22_[0]),
    .Q(state[0]),
    .R(1'b1),
    .S(_26_)
  );
  DFFSR _67_ (
    .CLK(_23_),
    .D(_22_[1]),
    .Q(state[1]),
    .R(_24_),
    .S(1'b1)
  );
  DFFSR _68_ (
    .CLK(_27_),
    .D(_22_[2]),
    .Q(state[2]),
    .R(_01_),
    .S(1'b1)
  );
  assign state[3] = 1'b0;
  assign cntr_load = state[0];
endmodule
